version: '3.7'

services:

  postgres_db:
    image: postgres:11
    ports:
      - 54321:5432
    environment:
      POSTGRES_DB: "patient"
      POSTGRES_USER: "demo"
      POSTGRES_PASSWORD: "demo"
    volumes:
      - ./.data:/var/lib/postgresql/data  
